---
resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: latest
resources:
- name: slack-alert
  type: slack-notification
  source:
    url: {{slack-hook}}
- name: resource-tutorial
  type: git
  source:
    uri: {{resource-tutorial}}
- name: resource-app
  type: git
  source:
    uri: {{resource-app}}
jobs:
- name: job-test-app
  public: true
  plan:
  - get: resource-tutorial
  - get: resource-app
    trigger: true
  - task: web-app-tests
    file: resource-tutorial/10_job_inputs/task_run_tests.yml
    on_failure:
      put: slack-alert
      params:
        channel: '#build_status'
        text: |
          The build had a result. Check it out at
          http://ci1.smallpdf-staging.com:8080/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME
          or at
          http://ci1.smallpdf-staging.com:8080/builds/$BUILD_ID
